#!/usr/bin/env node

/**
 * AetherGuard Interactive Setup Wizard
 * Run: npm run setup
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
});

function ask(question, defaultValue = '') {
    const suffix = defaultValue ? ` (default: ${defaultValue})` : '';
    return new Promise((resolve) => {
        rl.question(`${question}${suffix}: `, (answer) => {
            resolve(answer.trim() || defaultValue);
        });
    });
}

function print(msg) {
    console.log(msg);
}

function printHeader() {
    print('');
    print('='.repeat(50));
    print('  AetherGuard - Setup Wizard');
    print('='.repeat(50));
    print('');
    print('This wizard will help you configure the bot.');
    print('You will need:');
    print('  1. Discord Bot Token');
    print('  2. Discord Application (Client) ID');
    print('  3. Alchemy API Key');
    print('');
}

function checkNodeVersion() {
    const version = process.versions.node;
    const major = parseInt(version.split('.')[0], 10);
    if (major < 18) {
        print(`[ERROR] Node.js >= 18 required. Current: v${version}`);
        print('Download: https://nodejs.org/');
        process.exit(1);
    }
    print(`[OK] Node.js v${version}`);
}

function validateToken(token) {
    // Discord bot tokens have 3 parts separated by dots
    return token.split('.').length === 3;
}

function validateClientId(id) {
    return /^\d{17,20}$/.test(id);
}

function validateAlchemyKey(key) {
    return key.length >= 10;
}

function validateWalletAddress(addr) {
    return /^0x[a-fA-F0-9]{40}$/.test(addr);
}

async function main() {
    printHeader();
    checkNodeVersion();
    print('');

    // Check if .env already exists
    const envPath = path.join(__dirname, '..', '.env');
    if (fs.existsSync(envPath)) {
        const overwrite = await ask('A .env file already exists. Overwrite? (y/n)', 'n');
        if (overwrite.toLowerCase() !== 'y') {
            print('\nSetup cancelled. Your existing .env was not modified.');
            rl.close();
            return;
        }
    }

    // === Required Configuration ===
    print('\n--- Required Configuration ---\n');

    let discordToken = '';
    while (!validateToken(discordToken)) {
        discordToken = await ask('Discord Bot Token');
        if (!validateToken(discordToken)) {
            print('  [!] Invalid token format. Get it from: https://discord.com/developers/applications');
        }
    }
    print('  [OK] Token format valid');

    let clientId = '';
    while (!validateClientId(clientId)) {
        clientId = await ask('Discord Application (Client) ID');
        if (!validateClientId(clientId)) {
            print('  [!] Invalid Client ID. Should be a 17-20 digit number.');
        }
    }
    print('  [OK] Client ID valid');

    let alchemyKey = '';
    while (!validateAlchemyKey(alchemyKey)) {
        alchemyKey = await ask('Alchemy API Key');
        if (!validateAlchemyKey(alchemyKey)) {
            print('  [!] Invalid API key. Get one free at: https://www.alchemy.com/');
        }
    }
    print('  [OK] Alchemy key valid');

    // === Optional Configuration ===
    print('\n--- Optional Configuration (press Enter to skip) ---\n');

    const botOwnerId = await ask('Your Discord User ID (for /bot-stats)');
    if (botOwnerId && !validateClientId(botOwnerId)) {
        print('  [!] Warning: ID format looks incorrect, saving anyway');
    }

    const feedbackChannelId = await ask('Feedback Channel ID');

    const payReceiver = await ask('Payment receiver wallet address');
    if (payReceiver && !validateWalletAddress(payReceiver)) {
        print('  [!] Warning: Address format looks incorrect, saving anyway');
    }

    const payPrice = await ask('Subscription price (USDC/USDT)', '5');
    const subscriptionPhase = await ask('Subscription phase (beta/paid)', 'beta');

    // === Generate .env ===
    const envContent = [
        '# AetherGuard - Environment Configuration',
        '# Generated by setup wizard',
        '',
        '# ==================== Discord ====================',
        `DISCORD_TOKEN=${discordToken}`,
        `DISCORD_CLIENT_ID=${clientId}`,
        '',
        '# ==================== Alchemy ====================',
        `ALCHEMY_API_KEY=${alchemyKey}`,
        '',
        '# ==================== Database ====================',
        'DATABASE_PATH=./data.db',
        '',
        '# ==================== Activity ====================',
        'ACTIVITY_ENABLED=true',
        '',
        '# ==================== Subscription ====================',
        `SUBSCRIPTION_PHASE=${subscriptionPhase}`,
        'FOUNDING_LIMIT=50',
        '',
        '# ==================== Payment ====================',
        `PAYMENTS_ENABLED=${payReceiver ? 'true' : 'false'}`,
        `PAY_RECEIVER=${payReceiver}`,
        `PAY_PRICE=${payPrice}`,
        '',
        '# ==================== Optional ====================',
        `BOT_OWNER_ID=${botOwnerId}`,
        `FEEDBACK_CHANNEL_ID=${feedbackChannelId}`,
    ].join('\n') + '\n';

    fs.writeFileSync(envPath, envContent);
    print('\n[OK] .env file created successfully!');

    // === Check dependencies ===
    const nodeModulesPath = path.join(__dirname, '..', 'node_modules');
    if (!fs.existsSync(nodeModulesPath)) {
        print('\n[!] node_modules not found. Run: npm install');
    } else {
        print('[OK] Dependencies installed');
    }

    // === Print summary ===
    print('\n' + '='.repeat(50));
    print('  Setup Complete!');
    print('='.repeat(50));
    print('');
    print('Next steps:');
    print('  1. Make sure you enabled these Privileged Intents in Discord Developer Portal:');
    print('     - SERVER MEMBERS INTENT');
    print('     - MESSAGE CONTENT INTENT');
    print('');
    print('  2. Invite the bot to your server:');
    print(`     https://discord.com/api/oauth2/authorize?client_id=${clientId}&permissions=269569088&scope=bot%20applications.commands`);
    print('');
    print('  3. Start the bot:');
    print('     npm start');
    print('');
    print('  4. In your Discord server, run:');
    print('     /setup contract:<NFT_ADDRESS> chain:ethereum role:@YourRole amount:1');
    print('');

    rl.close();
}

main().catch((err) => {
    console.error('Setup failed:', err.message);
    rl.close();
    process.exit(1);
});
